/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        border: "hsl(var(--border))",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-blue-100",
    "bg-green-100",
    "bg-red-100",
    "bg-yellow-100",
    "bg-orange-100",
    "bg-purple-100",
    "bg-gray-100",
    "text-blue-600",
    "text-green-600",
    "text-red-600",
    "text-yellow-600",
    "text-orange-600",
    "text-purple-600",
    "text-gray-600",
    "text-blue-800",
    "text-green-800",
    "text-red-800",
    "text-yellow-800",
    "text-orange-800",
    "text-purple-800",
    "text-gray-800",
    "border-green-200",
    "border-red-200",
    "border-yellow-200",
    "border-gray-200",
    "border-l-red-500",
    "border-l-orange-500",
    "border-l-yellow-500",
    "border-l-blue-500",
  ],
}
